# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jaro/Desktop/Aisdi_Projekt1_Liniowe_Jaroslaw_Glegola

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jaro/Desktop/Aisdi_Projekt1_Liniowe_Jaroslaw_Glegola

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jaro/Desktop/Aisdi_Projekt1_Liniowe_Jaroslaw_Glegola/CMakeFiles /home/jaro/Desktop/Aisdi_Projekt1_Liniowe_Jaroslaw_Glegola/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jaro/Desktop/Aisdi_Projekt1_Liniowe_Jaroslaw_Glegola/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) -f CMakeFiles/check.dir/build.make CMakeFiles/check.dir/build
.PHONY : check/fast

#=============================================================================
# Target rules for targets named aisdiLinearTests

# Build rule for target.
aisdiLinearTests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aisdiLinearTests
.PHONY : aisdiLinearTests

# fast build rule for target.
aisdiLinearTests/fast:
	$(MAKE) -f CMakeFiles/aisdiLinearTests.dir/build.make CMakeFiles/aisdiLinearTests.dir/build
.PHONY : aisdiLinearTests/fast

#=============================================================================
# Target rules for targets named aisdiPerformanceTest

# Build rule for target.
aisdiPerformanceTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aisdiPerformanceTest
.PHONY : aisdiPerformanceTest

# fast build rule for target.
aisdiPerformanceTest/fast:
	$(MAKE) -f CMakeFiles/aisdiPerformanceTest.dir/build.make CMakeFiles/aisdiPerformanceTest.dir/build
.PHONY : aisdiPerformanceTest/fast

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/aisdiPerformanceTest.dir/build.make CMakeFiles/aisdiPerformanceTest.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/aisdiPerformanceTest.dir/build.make CMakeFiles/aisdiPerformanceTest.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/aisdiPerformanceTest.dir/build.make CMakeFiles/aisdiPerformanceTest.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

test/LinkedListTests.o: test/LinkedListTests.cpp.o

.PHONY : test/LinkedListTests.o

# target to build an object file
test/LinkedListTests.cpp.o:
	$(MAKE) -f CMakeFiles/aisdiLinearTests.dir/build.make CMakeFiles/aisdiLinearTests.dir/test/LinkedListTests.cpp.o
.PHONY : test/LinkedListTests.cpp.o

test/LinkedListTests.i: test/LinkedListTests.cpp.i

.PHONY : test/LinkedListTests.i

# target to preprocess a source file
test/LinkedListTests.cpp.i:
	$(MAKE) -f CMakeFiles/aisdiLinearTests.dir/build.make CMakeFiles/aisdiLinearTests.dir/test/LinkedListTests.cpp.i
.PHONY : test/LinkedListTests.cpp.i

test/LinkedListTests.s: test/LinkedListTests.cpp.s

.PHONY : test/LinkedListTests.s

# target to generate assembly for a file
test/LinkedListTests.cpp.s:
	$(MAKE) -f CMakeFiles/aisdiLinearTests.dir/build.make CMakeFiles/aisdiLinearTests.dir/test/LinkedListTests.cpp.s
.PHONY : test/LinkedListTests.cpp.s

test/VectorTests.o: test/VectorTests.cpp.o

.PHONY : test/VectorTests.o

# target to build an object file
test/VectorTests.cpp.o:
	$(MAKE) -f CMakeFiles/aisdiLinearTests.dir/build.make CMakeFiles/aisdiLinearTests.dir/test/VectorTests.cpp.o
.PHONY : test/VectorTests.cpp.o

test/VectorTests.i: test/VectorTests.cpp.i

.PHONY : test/VectorTests.i

# target to preprocess a source file
test/VectorTests.cpp.i:
	$(MAKE) -f CMakeFiles/aisdiLinearTests.dir/build.make CMakeFiles/aisdiLinearTests.dir/test/VectorTests.cpp.i
.PHONY : test/VectorTests.cpp.i

test/VectorTests.s: test/VectorTests.cpp.s

.PHONY : test/VectorTests.s

# target to generate assembly for a file
test/VectorTests.cpp.s:
	$(MAKE) -f CMakeFiles/aisdiLinearTests.dir/build.make CMakeFiles/aisdiLinearTests.dir/test/VectorTests.cpp.s
.PHONY : test/VectorTests.cpp.s

test/test_main.o: test/test_main.cpp.o

.PHONY : test/test_main.o

# target to build an object file
test/test_main.cpp.o:
	$(MAKE) -f CMakeFiles/aisdiLinearTests.dir/build.make CMakeFiles/aisdiLinearTests.dir/test/test_main.cpp.o
.PHONY : test/test_main.cpp.o

test/test_main.i: test/test_main.cpp.i

.PHONY : test/test_main.i

# target to preprocess a source file
test/test_main.cpp.i:
	$(MAKE) -f CMakeFiles/aisdiLinearTests.dir/build.make CMakeFiles/aisdiLinearTests.dir/test/test_main.cpp.i
.PHONY : test/test_main.cpp.i

test/test_main.s: test/test_main.cpp.s

.PHONY : test/test_main.s

# target to generate assembly for a file
test/test_main.cpp.s:
	$(MAKE) -f CMakeFiles/aisdiLinearTests.dir/build.make CMakeFiles/aisdiLinearTests.dir/test/test_main.cpp.s
.PHONY : test/test_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... check"
	@echo "... aisdiLinearTests"
	@echo "... rebuild_cache"
	@echo "... aisdiPerformanceTest"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... test/LinkedListTests.o"
	@echo "... test/LinkedListTests.i"
	@echo "... test/LinkedListTests.s"
	@echo "... test/VectorTests.o"
	@echo "... test/VectorTests.i"
	@echo "... test/VectorTests.s"
	@echo "... test/test_main.o"
	@echo "... test/test_main.i"
	@echo "... test/test_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

